Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [1]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array Indexing
print("Array Indexing:")
print(arr[0][1])

# Fancy Indexing
print("Fancy Indexing:")
print(arr[[0, 2], [1, 2]]) 

Array Indexing:
2
Fancy Indexing:
[2 9]


Q2. Execute the 2D array Slicing.

In [2]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
print("Slicing:")
print(arr[0:2, 1:3]) 


Slicing:
[[2 3]
 [5 6]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [3]:
import numpy as np

# Create a 5-dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print("The created array is:")
print(arr)
print("The number of dimensions of the array is:", arr.ndim)

The created array is:
[[[[[1 2 3 4]]]]]
The number of dimensions of the array is: 5


Q4. Reshape the array from 1-D to 2-D array.

In [4]:
import numpy as np

# Create a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2-D array
new_arr = arr.reshape(2, 3)

print("Original array:")
print(arr)

print("Reshaped array:")
print(new_arr)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [5]:
import numpy as np

# Create two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack the arrays using different functions
print("Stack():")
print(np.stack((a, b), axis=0))

print("hstack():")
print(np.hstack((a, b)))

print("vstack():")
print(np.vstack((a, b)))

print("dstack():")
print(np.dstack((a, b)))

Stack():
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
hstack():
[[1 2 5 6]
 [3 4 7 8]]
vstack():
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
dstack():
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Q6. Perform the searchsort method in Numpy array.


In [6]:
import numpy as np

# Create an input array
arr = np.array([2, 3, 4, 5, 6])

# Find the indices to maintain sorted array
out_ind = np.searchsorted(arr, 4)

print("Output indices to maintain sorted array:", out_ind)

Output indices to maintain sorted array: 2


Q7. Create Numpy Structured array using your domain features.

In [8]:
import numpy as np

# Define the data types for the fields
dt = np.dtype([('name', 'U20'), ('calories', 'i4'), ('fat', 'f4'), ('protein', 'f4'), ('carbs', 'f4')])

# Create a structured array
arr = np.array([('Apple', 95, 0.3, 0.5, 25), ('Banana', 105, 0.4, 1.3, 27)], dtype=dt)

print("The created structured array is:")
print(arr)

The created structured array is:
[('Apple',  95, 0.3, 0.5, 25.) ('Banana', 105, 0.4, 1.3, 27.)]


Q8. Create Data frame using List and Dictionary.

In [9]:
import pandas as pd

# Define the data as a list of dictionaries
data = [
    {'name': 'John', 'age': 25, 'gender': 'Male'},
    {'name': 'Jane', 'age': 30, 'gender': 'Female'},
    {'name': 'Bob', 'age': 35, 'gender': 'Male'},
    {'name': 'Alice', 'age': 40, 'gender': 'Female'}
]

# Create a DataFrame from the data
df = pd.DataFrame(data)

print("The created DataFrame is:")
print(df)

The created DataFrame is:
    name  age  gender
0   John   25    Male
1   Jane   30  Female
2    Bob   35    Male
3  Alice   40  Female


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [10]:
import pandas as pd
import numpy as np

# Create a dictionary with food data
food_data = {
    'name': ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes', 'Pineapple'],
    'calories': [95, 105, 62, 135, 52, 82],
    'fat': [0.3, 0.4, 0.2, 1.2, 0.2, 0.1],
    'protein': [0.5, 1.3, 1.2, 1.6, 0.7, 0.9],
    'carbs': [25, 27, 15, 30, 14, 22],
    'sugar': [19, np.nan, np.nan, np.nan, np.nan, np.nan]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(food_data)

# Check for missing data
print("Missing data:\n", df.isnull())
# Check for non-missing data
print("Non-missing data:\n", df.notnull())

# Drop rows with missing data
df.dropna(inplace=True)
print("After dropping rows with missing data:\n", df)

# Fill missing values with a specific value
df.fillna(0, inplace=True)
print("After filling missing values with zero:\n", df)

# Replace missing values with the mean of the column
df['sugar'].replace(np.nan, df['sugar'].mean(), inplace=True)
print("After replacing missing values with the mean of the column:\n", df)

# Interpolate missing values
df.interpolate(inplace=True)
print("After interpolating missing values:\n", df)

Missing data:
     name  calories    fat  protein  carbs  sugar
0  False     False  False    False  False  False
1  False     False  False    False  False   True
2  False     False  False    False  False   True
3  False     False  False    False  False   True
4  False     False  False    False  False   True
5  False     False  False    False  False   True
Non-missing data:
    name  calories   fat  protein  carbs  sugar
0  True      True  True     True   True   True
1  True      True  True     True   True  False
2  True      True  True     True   True  False
3  True      True  True     True   True  False
4  True      True  True     True   True  False
5  True      True  True     True   True  False
After dropping rows with missing data:
     name  calories  fat  protein  carbs  sugar
0  Apple        95  0.3      0.5     25   19.0
After filling missing values with zero:
     name  calories  fat  protein  carbs  sugar
0  Apple        95  0.3      0.5     25   19.0
After replacing missing v

C:\Users\Likitha Yadav G\AppData\Local\Temp\ipykernel_20072\2578643111.py:35: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(inplace=True)


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [11]:
import pandas as pd

# Create a dictionary with food data
food_data = {
    'name': ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes', 'Pineapple'],
    'calories': [95, 105, 62, 135, 52, 82],
    'fat': [0.3, 0.4, 0.2, 1.2, 0.2, 0.1],
    'protein': [0.5, 1.3, 1.2, 1.6, 0.7, 0.9],
    'carbs': [25, 27, 15, 30, 14, 22]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(food_data)

# Set the index to be the name column
df.set_index('name', inplace=True)

print("The created DataFrame with hierarchical index is:")
print(df)

The created DataFrame with hierarchical index is:
           calories  fat  protein  carbs
name                                    
Apple            95  0.3      0.5     25
Banana          105  0.4      1.3     27
Orange           62  0.2      1.2     15
Mango           135  1.2      1.6     30
Grapes           52  0.2      0.7     14
Pineapple        82  0.1      0.9     22
